site_name: Documentations
site_url: https://mydomain.org/mysite/

theme:
  name: material
  language: en
  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
   # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Loanbrwsk1

extra_css:
  - stylesheets/extra.css
  
plugins:
  - search
  - offline
